node:
  id: 1
  kind: gate-node-test
  address: 127.0.0.1
  port: 9002

logger:
  path: ./logs/app.log
  level: info
  printConsole: true
  file:
    maxSize: 50
    maxBackups: 100
    maxAge: 30
    compress: false
    localTime: true
gate:
  address: tcp://127.0.0.1:9002
  keepAlive: 60
  sendChanSize: 1024
  readBufSize: 4096
  maxConn: 10000

cluster:
  name: gas-node
  discovery:
    type: consul
    config:
      address: 127.0.0.1:8500
      watchWaitTime: 3s
      healthTTL: 3s
      deregisterInterval: 3s
  messageQueue:
    type: nats
    config:
      name: gas-node
      maxReconnects: -1
      reconnectWaitMs: 2000
      timeoutMs: 5000
      pingIntervalMs: 20000
      maxPingsOut: 2
      allowReconnect: true
      username: ""
      password: ""
      token: ""
      disableNoEcho: false
      retryOnFailedConnect: true
      servers:
        - nats://127.0.0.1:4222








