// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: actor.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	ActorName     string                 `protobuf:"bytes,2,opt,name=actorName,proto3" json:"actorName,omitempty"`
	ActorId       uint64                 `protobuf:"varint,3,opt,name=actorId,proto3" json:"actorId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pid) Reset() {
	*x = Pid{}
	mi := &file_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pid) ProtoMessage() {}

func (x *Pid) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pid.ProtoReflect.Descriptor instead.
func (*Pid) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{0}
}

func (x *Pid) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Pid) GetActorName() string {
	if x != nil {
		return x.ActorName
	}
	return ""
}

func (x *Pid) GetActorId() uint64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            *Pid                   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From          *Pid                   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Async         bool                   `protobuf:"varint,5,opt,name=async,proto3" json:"async,omitempty"`
	Deadline      int64                  `protobuf:"varint,6,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Session       *Session               `protobuf:"bytes,7,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_actor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetTo() *Pid {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Message) GetFrom() *Pid {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Message) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetAsync() bool {
	if x != nil {
		return x.Async
	}
	return false
}

func (x *Message) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *Message) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_actor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Agent         *Pid              `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Values        map[string]string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_actor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Session) GetAgent() *Pid {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *Session) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	SourceNode    uint64                 `protobuf:"varint,3,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_actor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{4}
}

func (x *EventEnvelope) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *EventEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventEnvelope) GetSourceNode() uint64 {
	if x != nil {
		return x.SourceNode
	}
	return 0
}

var File_actor_proto protoreflect.FileDescriptor

const file_actor_proto_rawDesc = "" +
	"\n" +
	"\vactor.proto\x12\x05actor\"U\n" +
	"\x03Pid\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\x04R\x06nodeId\x12\x1c\n" +
	"\tactorName\x18\x02 \x01(\tR\tactorName\x12\x18\n" +
	"\aactorId\x18\x03 \x01(\x04R\aactorId\"\xcd\x01\n" +
	"\aMessage\x12\x1a\n" +
	"\x02to\x18\x01 \x01(\v2\n" +
	".actor.PidR\x02to\x12\x1e\n" +
	"\x04from\x18\x02 \x01(\v2\n" +
	".actor.PidR\x04from\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x14\n" +
	"\x05async\x18\x05 \x01(\bR\x05async\x12\x1a\n" +
	"\bdeadline\x18\x06 \x01(\x03R\bdeadline\x12(\n" +
	"\asession\x18\a \x01(\v2\x0e.actor.SessionR\asession\"6\n" +
	"\bResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06errMsg\x18\x02 \x01(\tR\x06errMsg\"\xaa\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\x05agent\x18\x02 \x01(\v2\n" +
	".actor.PidR\x05agent\x122\n" +
	"\x06values\x18\x03 \x03(\v2\x1a.actor.Session.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\rEventEnvelope\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1f\n" +
	"\vsource_node\x18\x03 \x01(\x04R\n" +
	"sourceNodeB\aZ\x05./;pbb\x06proto3"

var (
	file_actor_proto_rawDescOnce sync.Once
	file_actor_proto_rawDescData []byte
)

func file_actor_proto_rawDescGZIP() []byte {
	file_actor_proto_rawDescOnce.Do(func() {
		file_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_actor_proto_rawDesc), len(file_actor_proto_rawDesc)))
	})
	return file_actor_proto_rawDescData
}

var file_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_actor_proto_goTypes = []any{
	(*Pid)(nil),           // 0: actor.Pid
	(*Message)(nil),       // 1: actor.Message
	(*Response)(nil),      // 2: actor.Response
	(*Session)(nil),       // 3: actor.Session
	(*EventEnvelope)(nil), // 4: actor.EventEnvelope
	nil,                   // 5: actor.Session.ValuesEntry
}
var file_actor_proto_depIdxs = []int32{
	0, // 0: actor.Message.to:type_name -> actor.Pid
	0, // 1: actor.Message.from:type_name -> actor.Pid
	3, // 2: actor.Message.session:type_name -> actor.Session
	0, // 3: actor.Session.agent:type_name -> actor.Pid
	5, // 4: actor.Session.values:type_name -> actor.Session.ValuesEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_actor_proto_init() }
func file_actor_proto_init() {
	if File_actor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_actor_proto_rawDesc), len(file_actor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_actor_proto_goTypes,
		DependencyIndexes: file_actor_proto_depIdxs,
		MessageInfos:      file_actor_proto_msgTypes,
	}.Build()
	File_actor_proto = out.File
	file_actor_proto_goTypes = nil
	file_actor_proto_depIdxs = nil
}
