// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: actor.proto

package iface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        uint64                 `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ServiceId     uint64                 `protobuf:"varint,3,opt,name=serviceId,proto3" json:"serviceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pid) Reset() {
	*x = Pid{}
	mi := &file_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pid) ProtoMessage() {}

func (x *Pid) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pid.ProtoReflect.Descriptor instead.
func (*Pid) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{0}
}

func (x *Pid) GetNodeId() uint64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Pid) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pid) GetServiceId() uint64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            *Pid                   `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From          *Pid                   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Session       *Session               `protobuf:"bytes,5,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_actor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetTo() *Pid {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Message) GetFrom() *Pid {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_actor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Agent         *Pid                   `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	Index         uint32                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	EntityId      int64                  `protobuf:"varint,4,opt,name=entityId,proto3" json:"entityId,omitempty"`
	Code          int64                  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	Mid           int64                  `protobuf:"varint,6,opt,name=mid,proto3" json:"mid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_actor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_actor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_actor_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Session) GetAgent() *Pid {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *Session) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Session) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *Session) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Session) GetMid() int64 {
	if x != nil {
		return x.Mid
	}
	return 0
}

var File_actor_proto protoreflect.FileDescriptor

const file_actor_proto_rawDesc = "" +
	"\n" +
	"\vactor.proto\x12\x05actor\"O\n" +
	"\x03Pid\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\x04R\x06nodeId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tserviceId\x18\x03 \x01(\x04R\tserviceId\"\x93\x01\n" +
	"\aMessage\x12\x1a\n" +
	"\x02to\x18\x01 \x01(\v2\n" +
	".actor.PidR\x02to\x12\x1e\n" +
	"\x04from\x18\x02 \x01(\v2\n" +
	".actor.PidR\x04from\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12(\n" +
	"\asession\x18\x05 \x01(\v2\x0e.actor.SessionR\asession\"4\n" +
	"\bResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x9b\x01\n" +
	"\aSession\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x04R\x06userId\x12 \n" +
	"\x05agent\x18\x02 \x01(\v2\n" +
	".actor.PidR\x05agent\x12\x14\n" +
	"\x05index\x18\x03 \x01(\rR\x05index\x12\x1a\n" +
	"\bentityId\x18\x04 \x01(\x03R\bentityId\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x03R\x04code\x12\x10\n" +
	"\x03mid\x18\x06 \x01(\x03R\x03midB\n" +
	"Z\b./;ifaceb\x06proto3"

var (
	file_actor_proto_rawDescOnce sync.Once
	file_actor_proto_rawDescData []byte
)

func file_actor_proto_rawDescGZIP() []byte {
	file_actor_proto_rawDescOnce.Do(func() {
		file_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_actor_proto_rawDesc), len(file_actor_proto_rawDesc)))
	})
	return file_actor_proto_rawDescData
}

var file_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_actor_proto_goTypes = []any{
	(*Pid)(nil),      // 0: actor.Pid
	(*Message)(nil),  // 1: actor.Message
	(*Response)(nil), // 2: actor.Response
	(*Session)(nil),  // 3: actor.Session
}
var file_actor_proto_depIdxs = []int32{
	0, // 0: actor.Message.to:type_name -> actor.Pid
	0, // 1: actor.Message.from:type_name -> actor.Pid
	3, // 2: actor.Message.session:type_name -> actor.Session
	0, // 3: actor.Session.agent:type_name -> actor.Pid
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_actor_proto_init() }
func file_actor_proto_init() {
	if File_actor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_actor_proto_rawDesc), len(file_actor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_actor_proto_goTypes,
		DependencyIndexes: file_actor_proto_depIdxs,
		MessageInfos:      file_actor_proto_msgTypes,
	}.Build()
	File_actor_proto = out.File
	file_actor_proto_goTypes = nil
	file_actor_proto_depIdxs = nil
}
